greeting:
  message: "hello"
quarkus:
  datasource:
    db-king: postgresql
    username: postgres
    password: admin
    jdbc:
      url: jdbc:postgresql://0.0.0.0:5432/capacitacao
  hibernate-orm:
    database:
      generation: drop-and-create