greeting:
  message: "hello"
quarkus:
  http:
    cors:
      ~: true
      origins: http://localhost:4200,http://localhost:8080,http://localhost:8081
      headers: accept, authorization, content-type, x-requested-with
      methods: GET, OPTIONS, POST, PUT, DELETE
  datasource:
    db-king: postgresql
    username: postgres
    password: admin
    jdbc:
      url: jdbc:postgresql://0.0.0.0:5432/capacitacao
  hibernate-orm:
    database:
      generation: drop-and-create